### ISSUE TITLE
Meta: Mid/long-term to-dos 

### ISSUE THREAD

**Issue by mozrt2** [70nyIT/stealth-safe#6]
This issue lists to-dos that will become separate issues once all other pending issues are resolved:
- [ ] Extend the solution to other ERC-4337 smart accounts 
- [ ] Look into options to deploy Stealth Safes at withdrawal instead of deploying before sending funds (main issue is to think about who then pays for gas to deploy the Safe)
- [ ] Propose inclusion of Umbra methods for multisig implementations directly into the Umbra.js library instead of the current class extensions
- [ ] Work on making Stealth Safes compatible with EIPs [5564](https://eips.ethereum.org/EIPS/eip-5564) and [6538](https://eips.ethereum.org/EIPS/eip-6538) and contribute to these standards to ensure they take into account smart accounts as stealth receivers
